service: hrbot-service
provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:GetParameters
      Resource: ""
  functions:
    main:
      handler: handler.main
      events:
        - http:
            path: bothr
            method: post
  plugins:
    - serverless-offline