service: read-aws-ssm-parameters
provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:GetParameters
      Resource: "arn:aws:ssm:ap-southeast-1:453047983468:parameter/*"
  functions:
    main:
      handler: handler.main
      events:
        - http:
            path: hrbot
            method: post
plugins:
  - serverless-offline